### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by cc82tia** [cc82tia/furima-28124#13]
### URL 
https://furima-28124.herokuapp.com

### Basic認証のID
admin
### パスワード 
2222

### 出品者用のメールアドレス
a@com
### パスワード 
a123456

### 購入者用のメールアドレス
b@com
### パスワード 
b123456

### 購入用カードの番号
4242424242424242
### 期限
12/24
### セキュリティコード
123

**Comment by tomonari94** [comment]
河合さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by cc82tia** [comment]
お忙しい中、ごかくにんありがとうございます。
